vintf: 4.19: Bump device manifest version to 6
Google removed[1] the obsolete FCM 5 and the minimum required
version is now 6.

ERROR: files are incompatible: Runtime info and framework
compatibility matrix are incompatible: Kernel FCM Version
is 5 and kernel version is 4.19.248, but the first kernel
FCM version allowed for kernel version 4.19.y is 6: Success

[1] https://android.googlesource.com/platform/hardware/interfaces/+/ce70a2afe5a1f984fc4ed2d882b14b6f43e1ee2a

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>