common-packages: Remove NfcNci
build/make/core/tasks/platform_availability_check.mk:37:
warning:  Following modules are requested to be installed.
But are not available for platform because they do not have
"//apex_available:platform" or they depend on other modules
that are not available for platform
Offending entries:
NfcNci:packages/modules/Nfc/NfcNci
In file included from build/make/core/main.mk:1215:
In file included from build/make/core/Makefile:7925:
build/make/core/tasks/platform_availability_check.mk:37:
error: Build failed.
01:57:38 ckati failed with: exit status 1

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>